import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "~/components/cores/navbar";
import Footer from "~/components/cores/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EFNOTE | Electronic Musical Instrument",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
